[repository]
# The name of the github organization / person owner, e.g. tauffer-consulting.
# Must be in lower-case letters
REGISTRY_NAME = "hpc"

# The name of this Pieces repository
REPOSITORY_NAME = "HPC"
REPOSITORY_LABEL = "1111一些通用的高性能计算模块"

# The version of this Pieces release
# Attention: changing this will create a new release
VERSION = "0.1.0"
